<?php

?>

<a name="0920"></a><h2 style="border-bottom: 2px #333 solid;padding: 4px;">Business Opportunity</h2>

<div style="font-size: 8pt; font-weight: bold; border-bottom : 1px #AFA078 solid; border-left : 1px #AFA078 solid;padding: 4px; background-color: #FFF6DF;background-image:url('/IMAGES/backgrounds/classifieds_back.gif');"> A GREAT OPPORTUNITY </div><div style="background-color: #fff; padding: 4px;margin-bottom: 14px;"> TO OWN YOUR OWN PET FOOD BUSINESS, turnkey for under $10K. For more information Call Julie Mutch Toll-Free 1-877-738-3287 Ext. 217 or (604) 518-7706, www.ripleesranch.com.</div>

<div style="font-size: 8pt; font-weight: bold; border-bottom : 1px #AFA078 solid; border-left : 1px #AFA078 solid;padding: 4px; background-color: #FFF6DF;background-image:url('/IMAGES/backgrounds/classifieds_back.gif');"> AMAZING NEW PRODUCT </div><div style="background-color: #fff; padding: 4px;margin-bottom: 14px;"> Energy Gold Mines $ Incredible Cash Profits! View FREE Brochure at www.energiservending.com. For Samples Call 1-800-661-1832.</div>

<div style="font-size: 8pt; font-weight: bold; border-bottom : 1px #AFA078 solid; border-left : 1px #AFA078 solid;padding: 4px; background-color: #FFF6DF;background-image:url('/IMAGES/backgrounds/classifieds_back.gif');"> BE A Travel Consultant from home</div><div style="background-color: #fff; padding: 4px;margin-bottom: 14px;"> Internet based, huge discounts on resorts, airfare, cruises. (Your own business, full training) Must be dependable; http://www.retirerichandready.com; 1-519-885-1065.</div>

<div style="font-size: 8pt; font-weight: bold; border-bottom : 1px #AFA078 solid; border-left : 1px #AFA078 solid;padding: 4px; background-color: #FFF6DF;background-image:url('/IMAGES/backgrounds/classifieds_back.gif');"> MATCO TOOLS </div><div style="background-color: #fff; padding: 4px;margin-bottom: 14px;"> IS LOOKING FOR FRANCHISEES IN YOUR AREA - Professional products with a complete Business System available to support you in becoming your own boss. Home-based business; Training & Support Programs. CALL TOLL-FREE 1-888-696-2826. www.gomatco.com.</div>

<a name="0929"></a><h2 style="border-bottom: 2px #333 solid;padding: 4px;">Employment</h2>

<div style="font-size: 8pt; font-weight: bold; border-bottom : 1px #AFA078 solid; border-left : 1px #AFA078 solid;padding: 4px; background-color: #FFF6DF;background-image:url('/IMAGES/backgrounds/classifieds_back.gif');"> CARPENTERS/REMODELERS </div><div style="background-color: #fff; padding: 4px;margin-bottom: 14px;"> $25+/hour. Canada's leading home repair/remodeling company is seeking carpenters, remodelers, skilled tradespeople (M/F) in major Ontario cities. Apply toll free 1-800-884-2639 or on-line www.handymanconnection.ca.</div>

<div style="font-size: 8pt; font-weight: bold; border-bottom : 1px #AFA078 solid; border-left : 1px #AFA078 solid;padding: 4px; background-color: #FFF6DF;background-image:url('/IMAGES/backgrounds/classifieds_back.gif');"> Jobs in Saskatchewan </div><div style="background-color: #fff; padding: 4px;margin-bottom: 14px;"> Fast Food counter staff $10.00 p/h we assist with housing and relocation. Email resume to manager@excelemployment.net or fax 403-770-1865. Positions also available in Alberta.</div>

<div style="font-size: 8pt; font-weight: bold; border-bottom : 1px #AFA078 solid; border-left : 1px #AFA078 solid;padding: 4px; background-color: #FFF6DF;background-image:url('/IMAGES/backgrounds/classifieds_back.gif');"> JOURNEYPERSON ELECTRICAL</div><div style="background-color: #fff; padding: 4px;margin-bottom: 14px;"> with previous supervisory experience required immediately for a well established construction company in Inuvik, Northwest Territories. Send resume to: Email: weitzel@northwestel.net; Fax: (867) 777-2981.</div>

<div style="font-size: 8pt; font-weight: bold; border-bottom : 1px #AFA078 solid; border-left : 1px #AFA078 solid;padding: 4px; background-color: #FFF6DF;background-image:url('/IMAGES/backgrounds/classifieds_back.gif');"> PLANT MACHINERY MAINTENANCE</div><div style="background-color: #fff; padding: 4px;margin-bottom: 14px;"> mechanic & junior mechanic (Millwright). Corporate Images is an innovative, fast growth, ready-to-assemble furniture manufacturer located in South Surrey, just outside Vancouver, BC. We are a team-oriented business striving to create a wide variety of quality RTA furniture products. We are currently looking for a Full Time Maintenance Mechanic and a Full Time Junior Maintenance Mechanic able to start as soon as possible. The successful candidate will have completed high school (or equivalent) and will also have completion on a college/CEGEP/vocational or technical training. 3-5 Years (1-2 years for Junior position) experience and Industrial Mechanic (Millwright) Certification is preferred. Must be able to read, speak, and write English proficiently. In this position you will assist with assembling, installing, and preventive maintenance of machinery and equipment, including start-up, shutdown, troubleshooting and testing. Also included is the operation of computer-controlled equipment, specialty welding, and computerized alignment. Please forward resume and cover letter to: Richard Fantin, Fax: 604-542-7651, E-mail: hra@sonax.ca.</div>

<div style="font-size: 8pt; font-weight: bold; border-bottom : 1px #AFA078 solid; border-left : 1px #AFA078 solid;padding: 4px; background-color: #FFF6DF;background-image:url('/IMAGES/backgrounds/classifieds_back.gif');"> SOUTH ROCK LTD</div><div style="background-color: #fff; padding: 4px;margin-bottom: 14px;"> is holding career fairs for EXPERIENCED PAVING, ROADBUILDING & CRUSHING PERSONNEL in the following locations: Windsor - Feb.29-Hilton Windsor; Hamilton - March 1 - Hamilton Convention Centre; Toronto/Vaughan - March 3 - Hilton Garden Inn (3201-7 Hwy. W., Vaughan); Oshawa - March 4 - Holiday Inn. All run 9a.m. - 4 p.m. For more information visit www.southrock.ca or call 403-293-9300.</div>

<div style="font-size: 8pt; font-weight: bold; border-bottom : 1px #AFA078 solid; border-left : 1px #AFA078 solid;padding: 4px; background-color: #FFF6DF;background-image:url('/IMAGES/backgrounds/classifieds_back.gif');"> Westcan Bulk Transport</div><div style="background-color: #fff; padding: 4px;margin-bottom: 14px;"> is hiring additional drivers to haul bulk commodities including asphalt and anhydrous ammonia throughout Western Canada on 6-8 week contracts with flexible start dates; some starting April 1. Apply early as hiring process takes 2-4 weeks. Rotating contracts and full-time employment are also available. Return travel provided; AZ license with minimum 3 years-7/8 axle experience; pre-employment medical/substance test. Apply online at www.westcanbulktransport.com quoting competition #00-08-0218OCNA. E-mail: wbthr@westcanbulk.ca. No access to Internet? Contact HR for an application at: 1-800-661-2855 or fax 780-472-6909.</div>

<div style="font-size: 8pt; font-weight: bold; border-bottom : 1px #AFA078 solid; border-left : 1px #AFA078 solid;padding: 4px; background-color: #FFF6DF;background-image:url('/IMAGES/backgrounds/classifieds_back.gif');"> ADDITIONAL INCOME</div><div style="background-color: #fff; padding: 4px;margin-bottom: 14px;"> Mystery Shoppers, customer service needed for retail stores, food industries and financial institution in most areas. Post-secondary students welcome. No fees. Application: www.cmarresearch.com.</div>

<div style="font-size: 8pt; font-weight: bold; border-bottom : 1px #AFA078 solid; border-left : 1px #AFA078 solid;padding: 4px; background-color: #FFF6DF;background-image:url('/IMAGES/backgrounds/classifieds_back.gif');"> HOME BASE TRAVEL AGENTS WANTED</div><div style="background-color: #fff; padding: 4px;margin-bottom: 14px;"> Work from home. Travel Agent experience is required. Must have own clientele. For further information contact Lynda at Marlin Travel Port Hope. Telephone 1-800-387-8747.</div>

<a name="0931"></a><h2 style="border-bottom: 2px #333 solid;padding: 4px;">Careers</h2>

<div style="font-size: 8pt; font-weight: bold; border-bottom : 1px #AFA078 solid; border-left : 1px #AFA078 solid;padding: 4px; background-color: #FFF6DF;background-image:url('/IMAGES/backgrounds/classifieds_back.gif');"> THE CITY OF REGINA</div><div style="background-color: #fff; padding: 4px;margin-bottom: 14px;"> Public Works Division is looking for several MANAGERS in various departments. Please check our website www.regina.ca for further information.</div>

<a name="0933"></a><h2 style="border-bottom: 2px #333 solid;padding: 4px;">Career Training</h2>

<div style="font-size: 8pt; font-weight: bold; border-bottom : 1px #AFA078 solid; border-left : 1px #AFA078 solid;padding: 4px; background-color: #FFF6DF;background-image:url('/IMAGES/backgrounds/classifieds_back.gif');">BARTENDING COURSES</div><div style="background-color: #fff; padding: 4px;margin-bottom: 14px;">Attestation Card and Certificate.  Master School <a href="http://www.bartending.com" target="_blank">www.bartending.com</a></div>

<div style="font-size: 8pt; font-weight: bold; border-bottom : 1px #AFA078 solid; border-left : 1px #AFA078 solid;padding: 4px; background-color: #FFF6DF;background-image:url('/IMAGES/backgrounds/classifieds_back.gif');"> TRAIN FOR A NEW CAREER </div><div style="background-color: #fff; padding: 4px;margin-bottom: 14px;"> in medical transcription. Work from home. 99% employment rate. Contact CanScribe today for a free information package. 1-800-466-1535. www.canscribe.com / info@canscribe.com.</div>
