<a name="0211"></a><h2 style="border-bottom: 2px #333 solid;padding: 4px;">Articles for Sale</h2>

<div style="font-size: 8pt; font-weight: bold; border-bottom : 1px #AFA078 solid; border-left : 1px #AFA078 solid;padding: 4px; background-color: #FFF6DF;background-image:url('/IMAGES/backgrounds/classifieds_back.gif');">NORTHERN BEAR SKIN RUG</div><div style="background-color: #fff; padding: 4px;margin-bottom: 14px;">Shot and skinned, by Eskimo hunter. Tanned  full head mount by Hawkins, Winnipeg. Assessed at $5000. Asking $2500. OBO. Email pictures available. 613-567-6146.</div>

<div style="font-size: 8pt; font-weight: bold; border-bottom : 1px #AFA078 solid; border-left : 1px #AFA078 solid;padding: 4px; background-color: #FFF6DF;background-image:url('/IMAGES/backgrounds/classifieds_back.gif');"> A FREE TELEPHONE SERVICE</div><div style="background-color: #fff; padding: 4px;margin-bottom: 14px;"> Get Your First Month Free. Bad Credit, Don't Sweat It. No Deposits. No Credit Checks. Call Freedom Phone Lines Today Toll-Free 1-866-884-7464.</div>

<div style="font-size: 8pt; font-weight: bold; border-bottom : 1px #AFA078 solid; border-left : 1px #AFA078 solid;padding: 4px; background-color: #FFF6DF;background-image:url('/IMAGES/backgrounds/classifieds_back.gif');"> ADD AND SAVE </div><div style="background-color: #fff; padding: 4px;margin-bottom: 14px;"> on home phone reconnection. Bad credit - no problem! Up to $30. off for new customers, plus lower monthly rates! Call Tembo 1-877-266-6398 or sign up online www.tembo.ca.</div>

<div style="font-size: 8pt; font-weight: bold; border-bottom : 1px #AFA078 solid; border-left : 1px #AFA078 solid;padding: 4px; background-color: #FFF6DF;background-image:url('/IMAGES/backgrounds/classifieds_back.gif');"> BUILDINGS FOR SALE</div><div style="background-color: #fff; padding: 4px;margin-bottom: 14px;"> "ROCK BOTTOM PRICES!" 25x30 Now $4800. 25x40 $6100. 30x40 $7300. 35x50 $9990. 35x70 $12,290. 40x80 $14,900. Others. CANADIAN MANUFACTURER since 1980...Pioneer Steel 1-800-668-5422.</div>

<div style="font-size: 8pt; font-weight: bold; border-bottom : 1px #AFA078 solid; border-left : 1px #AFA078 solid;padding: 4px; background-color: #FFF6DF;background-image:url('/IMAGES/backgrounds/classifieds_back.gif');"> FUTURE STEEL BUILDINGS</div><div style="background-color: #fff; padding: 4px;margin-bottom: 14px;"> Durable, Dependable, Pre-engineered, All-Steel Structures. Custom-made to suit your needs and requirements. Factory-Direct affordable prices. Call 1-800-668-8653 ext. 170 for free brochure.</div>

<div style="font-size: 8pt; font-weight: bold; border-bottom : 1px #AFA078 solid; border-left : 1px #AFA078 solid;padding: 4px; background-color: #FFF6DF;background-image:url('/IMAGES/backgrounds/classifieds_back.gif');"> HIGH SPEED INTERNET</div><div style="background-color: #fff; padding: 4px;margin-bottom: 14px;"> $18.95 / Month. Absolutely no ports are blocked. Unlimited Downloading. Up to 5Mps Download and 800Kbps Upload. ORDER TODAY AT www.acanac.ca or CALL TOLL-FREE: 1-866-281-3538.</div>

<div style="font-size: 8pt; font-weight: bold; border-bottom : 1px #AFA078 solid; border-left : 1px #AFA078 solid;padding: 4px; background-color: #FFF6DF;background-image:url('/IMAGES/backgrounds/classifieds_back.gif');"> HOT TUB, 2007</div><div style="background-color: #fff; padding: 4px;margin-bottom: 14px;"> loaded, all options, cover, warranty, new, still in wrap. Cost $9,000, Sell $4,900. 613-482-1719.</div>

<div style="font-size: 8pt; font-weight: bold; border-bottom : 1px #AFA078 solid; border-left : 1px #AFA078 solid;padding: 4px; background-color: #FFF6DF;background-image:url('/IMAGES/backgrounds/classifieds_back.gif');"> SAWMILLS from only $3,495.00 </div><div style="background-color: #fff; padding: 4px;margin-bottom: 14px;"> Convert your LOGS TO VALUABLE LUMBER with your own Norwood portable band sawmill. Log skidders also available. www.norwoodsawmills.ca/400t - FREE Information: 1-800-566-6899 Ext:400OT</div>

<div style="font-size: 8pt; font-weight: bold; border-bottom : 1px #AFA078 solid; border-left : 1px #AFA078 solid;padding: 4px; background-color: #FFF6DF;background-image:url('/IMAGES/backgrounds/classifieds_back.gif');"> STEEL BUILDINGS</div><div style="background-color: #fff; padding: 4px;margin-bottom: 14px;"> Factory Direct CLEARANCE, up to 30% off. 25x32, 30x40, 50x100 and more. CALL NOW for free shipping, Curvco Steel 1-888-753-6130.</div>

<a name="0225A"></a><h2 style="border-bottom: 2px #333 solid;padding: 4px;">Fur</h2>

<div style="font-size: 8pt; font-weight: bold; border-bottom : 1px #AFA078 solid; border-left : 1px #AFA078 solid;padding: 4px; background-color: #FFF6DF;background-image:url('/IMAGES/backgrounds/classifieds_back.gif');">BLACK RANCH MINK, $1500.</div><div style="background-color: #fff; padding: 4px;margin-bottom: 14px;">Mahogany Mink Trotter, with hood $1650. Both size 8/10. Mint condition. Please call  613-834-9464.</div>
