<a name="0132"></a><h2 style="border-bottom: 2px #333 solid;padding: 4px;">Travel</h2>

<div style="font-size: 8pt; font-weight: bold; border-bottom : 1px #AFA078 solid; border-left : 1px #AFA078 solid;padding: 4px; background-color: #FFF6DF;background-image:url('/IMAGES/backgrounds/classifieds_back.gif');"> ALL INCLUSIVE PACKAGES</div><div style="background-color: #fff; padding: 4px;margin-bottom: 14px;"> Book Online at www.canadatravels.com and save more on your vacations. Use code NCA74327 for discount or call us toll-free at 1-800-563-5722.</div>

<div style="font-size: 8pt; font-weight: bold; border-bottom : 1px #AFA078 solid; border-left : 1px #AFA078 solid;padding: 4px; background-color: #FFF6DF;background-image:url('/IMAGES/backgrounds/classifieds_back.gif');"> REMOTE FLY-IN FISHING </div><div style="background-color: #fff; padding: 4px;margin-bottom: 14px;"> OUTPOST CABINS: Great Walleye and Northern Pike. Only cabins on the lake. Great dates available. Air-Dale Flying Service, 705-254-9909.</div>

<div style="font-size: 8pt; font-weight: bold; border-bottom : 1px #AFA078 solid; border-left : 1px #AFA078 solid;padding: 4px; background-color: #FFF6DF;background-image:url('/IMAGES/backgrounds/classifieds_back.gif');"> RIVERBOAT CRUISING </div><div style="background-color: #fff; padding: 4px;margin-bottom: 14px;"> St. Lawrence & Ottawa River. The hassle free way to travel. Unpack once, relax & enjoy. Included: Shore excursions, great meals & nightly entertainment. 3, 5 & 6 nights. Private Staterooms. From $995. TICO# 2168740. DIAL-A-BROCHURE 1(800)267-7868. www.StLawrenceCruiseLines.com.</div>

<div style="font-size: 8pt; font-weight: bold; border-bottom : 1px #AFA078 solid; border-left : 1px #AFA078 solid;padding: 4px; background-color: #FFF6DF;background-image:url('/IMAGES/backgrounds/classifieds_back.gif');"> TIMESHARE FORECLOSURES</div><div style="background-color: #fff; padding: 4px;margin-bottom: 14px;"> Save 60-80% off Retail! Best Resorts & Seasons! Call for FREE catalogue today! 1-800-496-5964. Browse hundreds of worldwide properties online -- www.holidaygroup.com/ocn.</div>

<div style="font-size: 8pt; font-weight: bold; border-bottom : 1px #AFA078 solid; border-left : 1px #AFA078 solid;padding: 4px; background-color: #FFF6DF;background-image:url('/IMAGES/backgrounds/classifieds_back.gif');"> TIMESHARE RESALES </div><div style="background-color: #fff; padding: 4px;margin-bottom: 14px;"> Sell-Buy-Rent. World's largest timeshare resale broker. Stroman Realty - since 1979. Worldwide selection of resort properties. Call today toll-free 1-800-201-0864.</div>
